### ISSUE TITLE
Panic while running embedded migrations

### ISSUE THREAD

**Issue by nustiueudinastea** [bokwoon95/sqddl#6]
Hi there,

Thanks for this project! I have been trying sqddl for running embedded migrations and have hit the following issue:

```
 runtime error: index out of range [1] with length 1
github.com/bokwoon95/sqddl/ddl.(*MigrateCmd).runWithRetry.func1({0x140015e8b90?, 0x5?, 0x108b00da0?})
	/Users/al3x/code/goprojects/pkg/mod/github.com/bokwoon95/sqddl@v0.4.12-0.20240328175232-9a583d2c454e/ddl/migrate_cmd.go:428 +0x338
github.com/bokwoon95/sqddl/ddl.(*BatchInsert).ExecContext(0x140013c8bd0, {0x105ab7f58, 0x108b00da0}, {0x105ab1990, 0x14000f0ae80}, 0x140013c8d48)
	/Users/al3x/code/goprojects/pkg/mod/github.com/bokwoon95/sqddl@v0.4.12-0.20240328175232-9a583d2c454e/ddl/batch_insert.go:322 +0x101c
github.com/bokwoon95/sqddl/ddl.(*MigrateCmd).runWithRetry(0x140013c9440, 0x14000f0ae80, {0x140002146c0, 0x1, 0x2})
	/Users/al3x/code/goprojects/pkg/mod/github.com/bokwoon95/sqddl@v0.4.12-0.20240328175232-9a583d2c454e/ddl/migrate_cmd.go:424 +0x928
github.com/bokwoon95/sqddl/ddl.(*MigrateCmd).Run(0x140013c9440)
	/Users/al3x/code/goprojects/pkg/mod/github.com/bokwoon95/sqddl@v0.4.12-0.20240328175232-9a583d2c454e/ddl/migrate_cmd.go:312 +0x14f8
```

Somehow, there's an out of bound access at line 428, in ddl/migrate_cmd.go. I am generating the migrations from a bunch of go structs, and I only have the following two migration files:
* migration_01_tables.sql
* migration_01_tables.undo.sql

I run the embedded migrations as follows:
```
	migrateCmd := &ddl.MigrateCmd{
		Dialect: "mysql",
		DB:      db.GetSqlDB(),
		DirFS:   migrationsDir,
	}
	err = migrateCmd.Run()
	if err != nil {
		return fmt.Errorf("failed to run migrations: %v", err)
	}
```

Any ideas?

**Comment by bokwoon95** [comment]
Oh, thanks. After looking at the code for `(*MigrateCmd).run` (called by `(*MigrateCmd).runWithRetry`) I have determined that there is an instance where I accidentally shadow the loop variable `i` (which is the correct value) with an internal variable called `i` (which is the wrong value) which I end up returning instead. Hopefully, changing the internal variable to `j` so it doesn't shadow `i` would solve the panic.

**Comment by nustiueudinastea** [comment]
That did the trick, thank you so much!
